Router to ad
RichardDev101/weddingAds pull request #3
Opened 2023-07-03 13:19 UTC by RichardDev101

2023-07-04 07:43 UTC, chris-diesner requested changes
looks nice and works as expected - anyway please add key prop while u iterate

2023-07-04 07:43 UTC, chris-diesner commented on frontend/src/components/gallary/AdForm.tsx
> +import {businessCategories} from "../../enum/BusinessCategory";
remove unused import

2023-07-04 07:43 UTC, chris-diesner commented on frontend/src/components/gallary/Home.tsx
> +                    {allAds.map(ad => <AdCard ad={ad}/>)}
missing key prop e.g. key={ad.id}

2023-07-04 08:05 UTC, chris-diesner commented on frontend/src/model/Advertisement.ts
> +    personsID: String
string instead of String

2023-07-05 08:49 UTC, RichardDev101 commented on frontend/src/components/gallary/AdForm.tsx
> +import {businessCategories} from "../../enum/BusinessCategory";
has been removed

2023-07-05 08:49 UTC, RichardDev101 commented on frontend/src/components/gallary/Home.tsx
> +                    {allAds.map(ad => <AdCard ad={ad}/>)}
has been added

2023-07-05 08:50 UTC, RichardDev101 commented on frontend/src/model/Advertisement.ts
> +    personsID: String
thx, has been changed to "string"

2023-07-05 08:56 UTC, chris-diesner approved these changes

2023-07-05 08:56 UTC, chris-diesner approved these changes

2023-07-05 09:17 UTC, merged